### The basics

In [1]:
import torch
import math

In [2]:
r = torch.zeros(5, 3)
print(r)
print(r.dtype)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])
torch.float32


In [3]:
i = torch.ones((5, 3), dtype=torch.int16)
i

tensor([[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]], dtype=torch.int16)

In [4]:
torch.manual_seed(1729)
r1 = torch.rand(2, 2)
print('A random tensor: ')
print(r)

r2 = torch.rand(2, 2)
print('Another random tensor: ')
print(r2)

torch.manual_seed(1729)
r3 = torch.rand(2, 2)
print(r3)

A random tensor: 
tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])
Another random tensor: 
tensor([[0.4216, 0.0691],
        [0.2332, 0.4047]])
tensor([[0.3126, 0.3791],
        [0.3087, 0.0736]])


In [5]:
ones = torch.ones(2, 3)
print(ones)

twos = torch.ones(2, 3) * 2
print(twos)

threes = ones + twos
print(threes)
print(threes.shape)

r1 = torch.rand(2, 3)
r2 = torch.rand(3, 2)

r3 = r1 + r2

tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[2., 2., 2.],
        [2., 2., 2.]])
tensor([[3., 3., 3.],
        [3., 3., 3.]])
torch.Size([2, 3])


RuntimeError: The size of tensor a (3) must match the size of tensor b (2) at non-singleton dimension 1

In [ ]:
r = torch.rand(2, 2) - 0.5 * 2
print(r)

print(torch.abs(r))
print(torch.asin(r))
print(torch.det(r))
print(torch.svd(r))
print(torch.std_mean(r))
print(torch.max(r))

tensor([[-0.5996, -0.0123],
        [-0.9648, -0.9095]])
tensor([[0.5996, 0.0123],
        [0.9648, 0.9095]])
tensor([[-0.6430, -0.0123],
        [-1.3046, -1.1421]])
tensor(0.5335)
torch.return_types.svd(
U=tensor([[-0.3432, -0.9393],
        [-0.9393,  0.3432]]),
S=tensor([1.4048, 0.3798]),
V=tensor([[ 0.7915,  0.6111],
        [ 0.6111, -0.7915]]))
(tensor(0.4368), tensor(-0.6215))
tensor(-0.0123)


### Pytorch Tensors

In [6]:
x = torch.empty(3, 4)
x # garbage memory

tensor([[2.1610e+27, 3.5863e-41, 0.0000e+00, 0.0000e+00],
        [       nan, 3.5872e-41, 3.9890e+03, 1.7033e+19],
        [1.0903e+27, 4.3608e+27, 2.7067e+23, 7.4937e+31]])

In [7]:
zeroes = torch.zeros(2, 3)
print(zeroes)

tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [8]:
torch.manual_seed(1111)
random = torch.rand(2, 3)
random

tensor([[0.4606, 0.0850, 0.8009],
        [0.3972, 0.9548, 0.5982]])

In [9]:
x = torch.empty(2, 3, 4)
print(x.shape)

torch.Size([2, 3, 4])


In [10]:
x

tensor([[[1.7281e+27, 3.5863e-41, 0.0000e+00, 0.0000e+00],
         [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00],
         [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00]],

        [[0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00],
         [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00],
         [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00]]])

In [11]:
k = torch.rand_like(x)
k

tensor([[[0.4821, 0.9446, 0.5145, 0.8125],
         [0.3122, 0.9756, 0.8747, 0.7186],
         [0.3945, 0.4090, 0.8398, 0.7494]],

        [[0.8129, 0.3084, 0.3856, 0.0044],
         [0.3022, 0.1679, 0.3270, 0.7481],
         [0.7058, 0.7362, 0.4007, 0.3604]]])

In [12]:
a = torch.ones((2, 3), dtype=torch.int16)
a

tensor([[1, 1, 1],
        [1, 1, 1]], dtype=torch.int16)

In [13]:
b = torch.ones((2, 3), dtype=torch.float64)
b

tensor([[1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)

In [14]:
ones = torch.zeros(2, 2) + 1

ones

tensor([[1., 1.],
        [1., 1.]])

In [15]:
twos = torch.ones(2, 2) + 2
twos

tensor([[3., 3.],
        [3., 3.]])

#### Broadcasting

In [21]:
rand = torch.ones(2, 4)
doubled = rand * (torch.ones(1, 4) * 2)
print(rand)
print(doubled)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.]])
tensor([[2., 2., 2., 2.],
        [2., 2., 2., 2.]])
